stage: development

appId: # app id registered in app-store
appSecret: # app secret issued by a manager

api:
  public:
    http:
      port: 3021

appStore:
  baseUrl: http://localhost:3020

bot:
  name: AppTutorialBot
