stage: development

appId: # app id registered in app-store
appSecret: # app secret issued by a manager

clientId: # client id for manager type; legacy

api:
  public:
    http:
      port: 3022

appStore:
  baseUrl: http://localhost:3020

bot:
  name: AppTutorialBot
